Use virustotal in fetch

diff --git a/bash/fetch b/bash/fetch
--- a/bash/fetch
+++ b/bash/fetch
@@ -1,4 +1,5 @@
 #!/bin/bash
+set -eo pipefail
 
 ###
 # Downloads a web file and then opens it
@@ -12,16 +13,20 @@
 function warningmsg() {
     echo
     echo -e '\033[31;1m--WARNING--'
-    echo 'ONLY USE WITH TRUSTED FILES AND WEBSITES!'
-    echo 'SUPER-DUPER INSECURE!!!'
+    echo 'DO NOT DISABLE THE VIRUSTOTAL CHECK UNLESS ABSOLUTELY SURE!'
+    echo "THAT'S SUPER-DUPER RISKY!!!"
     echo -e '--WARNING--\033[0m'
     echo
 }
 
 # Show usage if run without arguments, too many arguments,
 # or when asked for help
-if [[ ($# -ne 1 && $# -ne 2) || $1 == '--help' ]]; then
-    echo 'Usage: fetch "URL" [dest-dir]'
+if [[ ($# -ne 1 && $# -ne 2 && $# -ne 3) || $1 == '--help' ]]; then
+    echo 'Usage: fetch "URL" [--no-vt] [dest-dir]'
+    echo -e "[--no-vt]\tDo not check the file with virustotal  \033[31;1mNOT RECOMMENDED!\033[0m"
+    echo -e '[dest-dir]\tDestination directory'
+    echo -e '\nEither have the env var $VT_API_KEY set with your virustotal'
+    echo 'API key, or input it at the prompt'
     warningmsg
     exit 0
 fi
@@ -33,26 +38,97 @@ if [ $1 == '--mean' ]; then
 fi
 
 # Warn the user and get confirmation before starting
-WARNPROMPT=`echo -e '\033[32mSure you want to continue? (y|Y to continue): \033[0m'`
-warningmsg
-read -t 30 -p "$WARNPROMPT"
-if [[ $REPLY =~ ^[yY] ]]; then
-    echo -e "\nYou asked for it..\n"
-else
-    echo -e "\nAborting..\n"
-    exit 0
-fi
+function confirmnovt() {
+    WARNPROMPT=`echo -e '\033[32mSure you want to continue? (y|Y to continue): \033[0m'`
+    warningmsg
+    read -t 30 -p "$WARNPROMPT"
+    if [[ $REPLY =~ ^[yY] ]]; then
+        echo -e "\nYou asked for it..\n"
+    else
+        echo -e "\nAborting..\n"
+        exit 0
+    fi
+}
 
 # Decode the filename and prepend the directory
 function urldecode() {
-    echo "$1/$(: "${_##*/}"; : "${_//+/ }"; echo -e "${_//%/\\x}")"
+    echo "$2/$(: "${1##*/}"; : "${_//+/ }"; echo -e "${_//%/\\x}")"
+}
+
+# Use virustotal unless explicitly refused
+function vtupload() {
+    # If file is too big, exit and tell user to open at own risk
+    if [[ $(ls -l "$1" | awk '{print $5}') -gt 650000000 ]]; then
+        echo -e '\033[31mFile is too large to scan with virustotal'
+        echo -e 'Open at your own risk\033[0m'
+        exit 1
+    fi
+
+    # Get API key
+    if [ -z "$VT_API_KEY" ]; then
+        echo -e '\033[31mEnvironment variable $VT_API_KEY is not set\033[0m'
+        read -s -p 'Input your API key now (<Enter> or <Ctrl-C> to abort): ' VT_API_KEY EXCESSWORDS
+        echo
+        if [ -z "$VT_API_KEY" ]; then
+            echo -e "\nAborting..\n"
+            exit 2
+        fi
+    fi
+
+    # Grab upload URL
+    echo
+    echo -e "Uploading to virustotal..\n"
+    UPLOAD_URL=`curl -sSfL -H "x-apikey: $VT_API_KEY" \
+        -H "Accept: application/json" \
+        "https://www.virustotal.com/api/v3/files/upload_url" |\
+        jq '.data' | tr -d '"'`
+    # Grab analysis report URL
+    ANALYSIS=`curl -fL --progress-bar \
+        -H "x-apikey: $VT_API_KEY" \
+        -H "Content-Type: multipart/form-data" \
+        -H "Accept: application/json" -F file=@"$1" \
+        "$UPLOAD_URL" | tee /tmp/vtAnalysisURL.json`
+    ANALYSISURL=`jq '.data.links.self' /tmp/vtAnalysisURL.json | tr -d '"'`
+    rm /tmp/vtAnalysisURL.json
+    # Grab suspicious and malicious stats
+    curl -sSfL -o /tmp/vtAnalysisReport.json \
+        -H "x-apikey: $VT_API_KEY" \
+        -H "Accept: application/json" "$ANALYSISURL"
+    SUS=`jq '.data.attributes.stats.suspicious' /tmp/vtAnalysisReport.json`
+    MAL=`jq '.data.attributes.stats.malicious' /tmp/vtAnalysisReport.json`
+    rm /tmp/vtAnalysisReport.json
+
+    # If unsafe, warn user and exit
+    if [[ $SUS -gt 0 || $MAL -gt 0 ]]; then
+        echo -e "\n\033[31;1m$(($SUS+$MAL)) scans found this file suspicious \
+        and/or malicious"
+        echo -e "Open at your own risk\033[0m"
+        exit 3
+    fi
+
+    # File checks out, continue
+    echo -e "\n\033[32mFile checks out, opening..\033[0m"
 }
 
 # wget and then open the file
-if [ $# -eq 2 ]; then
-    wget -nc -P "$2" "$1"
-    open "$(urldecode "$2")"
+echo
+if [[ $# -eq 1 ]]; then
+    wget -q --show-progress -nc "$1"
+    vtupload "$(urldecode "$1" .)"
+    open "$(urldecode "$1" .)"
+elif [[ $# -eq 2 && $2 != '--no-vt' ]]; then
+    wget -q --show-progress -nc -P "$2" "$1"
+    vtupload "$(urldecode "$1" "$2")"
+    open "$(urldecode "$1" "$2")"
+elif [[ $# -eq 2 && $2 == '--no-vt' ]]; then
+    wget -q --show-progress -nc "$1"
+    confirmnovt
+    open "$(urldecode "$1" .)"
+elif [[ $# -eq 3 && $2 == '--no-vt' ]]; then
+    wget -q --show-progress -nc -P "$3" "$1"
+    confirmnovt
+    open "$(urldecode "$1" "$3")"
 else
-    wget -nc "$1"
-    open "$(urldecode .)"
+    echo "Second argument ($2) not recognized, aborting.."
+    exit 4
 fi
